- README.md
- config/chart/samsahai/templates/clusterrole-rbac.yaml
- internal/samsahai/k8sobject/object.go
- internal/staging/collect_result.go
- internal/staging/util.go
- pkg/samsahai/rpc/service.pb.go
- pkg/samsahai/rpc/service.twirp.go
- pkg/staging/rpc/service.pb.go
- pkg/staging/rpc/service.twirp.go
- Fix RPC unauthorized error
- Add permission for logs
none
> :bug: [patch] Fix RPC unauthorized error

- README.md
- Add link to article on medium
none
> :memo: Add link to article on medium

- internal/log/log.go
- internal/samsahai/activepromotion/collect_result.go
- internal/samsahai/activepromotion/environment_cleanup.go
- internal/samsahai/controller.go
- internal/staging/controller.go
- internal/staging/deploy/helm3/engine.go
- Fix deleting helm releases improperly due to release not found
> :bug: Fix deleting helm releases improperly

- README.md
- cmd/samsahai/main.go
- Fix s2h staging default image to have `v` in tag
- Update missing document
**Related issue link**: https://github.com/agoda-com/samsahai/issues/16
> :bug: [patch] Fix s2h staging default image

- internal/staging/deploy.go
- Handle queue error when a component does not exist
> :bug: Fix staging controller crash due to component missing

- internal/queue/controller.go
- internal/staging/collect_result.go
- internal/staging/controller.go
- internal/staging/util.go
- Update queue history before deleting queue to have more queue information
- Add more logs
> :bento: [patch] Update queue history before deleting queue

- test/e2e/samsahai/ctrl.go
> :bug: [patch] Handle flaky test

- internal/errors/errors.go
- internal/samsahai/activepromotion/controller.go
- internal/samsahai/activepromotion/queue.go
- internal/samsahai/activepromotion/util.go
- test/e2e/samsahai/ctrl.go
- Fix active promotion flow stuck due to queue working incorrectly
> :bug: [patch] Fix active promotion queue out of reconcile

- internal/errors/errors.go
- internal/samsahai/controller.go
- test/e2e/samsahai/ctrl.go
- test/e2e/staging/ctrl.go
- Fix flaky e2e test on staging controller
none
> :zap: Fix flaky test

- config/chart/samsahai/templates/clusterrole-rbac.yaml
- config/chart/samsahai/templates/podsecuritypolicy.yaml
- config/chart/samsahai/values.yaml
- Add podsecuritypolicy for Samsahai chart
> ☸️ Add podsecuritypolicy

- internal/samsahai/exporter/metric.go
> :bug: [patch] Fix wrong removing queue metric

- internal/samsahai/activepromotion/controller.go
- internal/staging/controller.go
- internal/util/runtime_object.go
- Change the way of cleaning up service since got error `the server does not allow this method on the requested resource`
> :bug: [patch] Fix force deleting service due to method not allowed

- internal/reporter.go
- internal/reporter/msteams/reporter.go
- internal/reporter/msteams/reporter_test.go
- internal/reporter/reportermock/reporter.go
- internal/reporter/rest/reporter.go
- internal/reporter/rest/reporter_test.go
- internal/reporter/shell/reporter.go
- internal/reporter/shell/reporter_test.go
- internal/reporter/slack/reporter.go
- internal/reporter/slack/reporter_test.go
- internal/samsahai/internal_process.go
- Support component name and more params in image missing reporter
> :bento: [patch] Support more params in image missing reporter

- api/v1beta1/activepromotion_types.go
- api/v1beta1/team_types.go
- config/crds/env.samsahai.io_activepromotionhistories.yaml
- config/crds/env.samsahai.io_activepromotions.yaml
- go.mod
- go.sum
- internal/samsahai/controller.go
- test/e2e/samsahai/ctrl.go
- Should trigger active promotion / notify component changed / run post namespace creation once after creating team/namespace
> :bug: [patch] Fix auto promoting after creating team

- internal/config/controller.go
- internal/config/controller_test.go
- test/e2e/samsahai/ctrl.go
- Fix unable to delete and create cronjob with the same cronjob name (will get `alreadyExisted` error)
> :bug: [patch] Fix unable to delete and create cronjob with same name

- internal/config/controller.go
- internal/config/controller_test.go
- Decrease successful jobs history limit to 1
> :bento: [patch] Decrease successful jobs history limit to 1

- internal/staging/collect_result.go
-  Add ingress into deployment logs
> :loud_sound: [patch] Add ingress into deployment logs

- internal/config/controller.go
- Decrease successful jobs history limit to 0
> :bento: [patch] Decrease successful jobs history limit to 0

- README.md
- cmd/samsahai/main.go
- examples/README.md
- examples/configs/crds/active-promotion-example.yaml
- examples/configs/crds/config-example.yaml
- examples/configs/crds/team-example-local.yaml
- examples/configs/crds/team-example.yaml
- examples/envs/active/redis.yaml
- examples/envs/base/wordpress.yaml
- examples/envs/pre-active/redis.yaml
- examples/envs/staging/redis.yaml
- examples/starter/crds/active-promotion.yaml
- examples/starter/crds/config.yaml
- examples/starter/crds/secret.yaml
- examples/starter/crds/team.yaml
- Add example integration configuration
- Increase active promotion timeout into 60m
> :bulb: Add example integration configuration

- README.md
- examples/starter/crds/config.yaml
- Add more feature description
> :bulb: Add more feature description

- internal/staging/controller.go
- internal/staging/deploy.go
- Check job completeness instead of running
> :bug: [patch] Check job completeness

- internal/reporter/msteams/reporter.go
- internal/reporter/msteams/reporter_test.go
- internal/reporter/slack/reporter.go
- internal/reporter/slack/reporter_test.go
- internal/staging/collect_result.go
- Fix duplicated components for init container issue
- Adjust reporter message for init container issue
> :bug: [patch] Fix duplicated components for init container issue

- internal/desiredcomponent/controller.go
- Fix triggering desired components every time bug
> :bug: [patch] Fix triggering desired components every time

- .github/CODEOWNERS
- .github/workflows/build-test-release.yml
- Fix ci failed due to ssh-agent step
- Add more code owner
> :green_heart: Upgrade ssh agent version

- README.md
- config/chart/samsahai/values.yaml
- examples/configs/crds/config-example.yaml
- examples/starter/crds/config.yaml
- Change crds' example URLs to be internal
> :pencil: Update config example URLs

- internal/config/controller_test.go
- internal/util/template/render.go
- internal/util/template/render_test.go
- Modify template render to support missing values
- Fix values template render conflict with helm template
> :bug: [patch] Fix values file template render to support missing values

- internal/staging/collect_result.go
- Ignore deployment issues if deploy engine is mock
> :bento: [patch] Ignore deployment issues if deploy engine is mock

- README.md
- internal/samsahai/webhook/pullrequest.go
- Add return on error triggering pr webhook
- Fix readme headers
> :pencil: [patch] Add return on error & fix readme headers

- internal/staging/deploy.go
- test/e2e/pullrequest/ctrl.go
- Fix pr values override in the wrong order
> :bug: [patch] Fix pr values override

- internal/errors/errors.go
- internal/samsahai/pullrequest.go
- internal/samsahai/webhook/pullrequest.go
- test/e2e/pullrequest/ctrl.go
- Validate pull request bundle name whether it exists in configuration or not
> :children_crossing: Add pull request trigger validation

- cmd/samsahai/main.go
- internal/samsahai/controller.go
- internal/staging/deploy.go
- Not return an error if helm validation timeout
- Increase helm validation timeout
- Fix team creation error when config not exist
> :adhesive_bandage: [patch] Not return an error if helm validation timeout

- internal/staging/deploy.go
- Fix helm validation timeout too short from 5 seconds to 5 minutes
> :bug: [patch] Fix helm validation timeout too short

- internal/samsahai/checker/harbor/checker.go
- internal/samsahai/checker/harbor/checker_test.go
- Upgrade harbor api version to v2.0
- Update list tags endpoint
> :arrow_up: [patch] Upgrade harbor api version to v2.0

- internal/samsahai/checker/harbor/checker.go
- Increase image page size of harbor from 1 to 100
> :adhesive_bandage: [patch] Increase image page size of harbor

- internal/samsahai/webhook/team.go
- Sort teams returning from API
> :bento: [patch] Sort teams returning from API

- internal/staging/deploy.go
- internal/staging/util.go
- Continue proceed queue even queue not found while deleting
> :adhesive_bandage: Ignore queue not found error while deleting queue

- .gitlab-ci.yml
- Add release webhook for GitLab CI
> :green_heart: Add release webhook for gitlab ci

- internal/staging/collect_result.go
- test/e2e/staging/ctrl.go
- Add events into deployment zip logs
> :bento: [patch] Add events into deployment zip logs

- .gitlab-ci.yml
- Delaying release pipeline after pushing tag
> :green_heart: Delaying release pipeline after pushing tag

- internal/samsahai/k8sobject/object.go
- Add destinationrules rule into role
> :wheel_of_dharma: [patch] Add destinationrules rule into role

- api/v1/queue_types.go
- internal/samsahai/activepromotion/deploy.go
- internal/staging/start_testrunner.go
- internal/staging/testrunner/gitlab/testrunner.go
- Support multiple test runners
> :bug: Support running multiple test runners

- cmd/samsahai/main.go
- cmd/staging/main.go
- internal/const.go
- internal/samsahai.go
- internal/samsahai/controller.go
- internal/staging/controller.go
- internal/staging/testrunner/gitlab/testrunner.go
- test/e2e/pullrequest/ctrl.go
- test/e2e/samsahai/ctrl.go
- test/e2e/staging/ctrl.go
- Add GitLab token configuration to get result from private GitLab project
> :bug: [patch] Fix getting result from private gitlab project

- internal/reporter/msteams/reporter.go
- internal/reporter/slack/reporter.go
- Update Slack & Teams report message
> :speech_balloon: [patch] Update Slack & Teams report message

- examples/starter/crds/config.yaml
- Fix the wrong indent of config starter
> fix indent tearDownDuration in pull request and bundle on starter

- api/v1/config_types.go
- api/v1/team_types.go
- cmd/samsahai/main.go
- config/chart/samsahai/values.yaml
- config/crds/env.samsahai.io_configs.yaml
- config/crds/env.samsahai.io_teams.yaml
- examples/starter/crds/config.yaml
- examples/starter/crds/secret.yaml
- examples/starter/crds/team.yaml
- internal/reporter/gitlab/reporter.go
- internal/reporter/gitlab/reporter_test.go
- internal/samsahai.go
- internal/samsahai/controller.go
- internal/util/gitlab/gitlab.go
- internal/util/gitlab/gitlab_test.go
* Publish test report to Gitlab for Pull Request trigger
> feat: mr report to Gitlab

- go.mod
- test/e2e/pullrequest/ctrl.go
- test/e2e/staging/ctrl.go
- Fix go.mod
- run `make tidy`
- Release previous PR
> 🐛  [minor] Fix go.mod

- config/crds/env.samsahai.io_configs.yaml
- config/crds/env.samsahai.io_pullrequestqueuehistories.yaml
- config/crds/env.samsahai.io_pullrequestqueues.yaml
- config/crds/env.samsahai.io_pullrequesttriggers.yaml
- config/crds/env.samsahai.io_queuehistories.yaml
- config/crds/env.samsahai.io_queues.yaml
- config/crds/env.samsahai.io_teams.yaml
- internal/staging/start_testrunner.go
- internal/staging/testrunner/gitlab/testrunner.go
- test/data/crds/env.samsahai.io_configs.yaml
- test/data/crds/env.samsahai.io_pullrequestqueuehistories.yaml
- test/data/crds/env.samsahai.io_pullrequestqueues.yaml
- test/data/crds/env.samsahai.io_pullrequesttriggers.yaml
- test/data/crds/env.samsahai.io_queuehistories.yaml
- test/data/crds/env.samsahai.io_queues.yaml
- test/data/crds/env.samsahai.io_teams.yaml
- Fix could not get test result due to start time is empty
- Generate crds
> 🐛  [patch] Fix could not get test result due to start time is empty

- Makefile
- go.mod
- go.sum
- internal/deploy.go
> [patch] shorten release name to support job suffix

- internal/deploy.go
- internal/samsahai/activepromotion/environment_cleanup.go
- internal/samsahai/controller.go
- internal/samsahai/rpc.go
- internal/staging/collect_result.go
- internal/staging/controller.go
- internal/staging/util.go
- test/e2e/staging/ctrl.go
> [patch] Remove namespace name from release name

- go.mod
- go.sum
- internal/deploy.go
- internal/staging/deploy.go
- internal/staging/deploy/helm3/engine.go
- internal/staging/deploy/helm3/engine_test.go
- internal/staging/deploy/mock/engine.go
- Wait for pre-hook jobs finished before continuing
> :bento: [patch] Wait for pre-hook jobs finished before continuing

- internal/staging/deploy.go
…est queue
- Verify at least one service deployed before deploying services from active environment
> :adhesive_bandage: [patch] Verify at least one service deployed for pr queue

- internal/staging/util.go
- test/e2e/staging/ctrl.go
> [patch] fix: remove testrunnerOverride condition

- internal/staging/testrunner/gitlab/testrunner.go
Add the retrying logic when getting the result if a server error
> [patch] fix: add get result retrying process
